clear

echo -e "\e[31m"
echo "              uuuuuuu"
echo "          uu$$$$$$$$$$$uu"
echo "       uu$$$$$$$$$$$$$$$$$uu"
echo "      u$$$$$$$$$$$$$$$$$$$$$u"
echo "     u$$$$$$$$$$$$$$$$$$$$$$$u"
echo "    u$$$$$$$$$$$$$$$$$$$$$$$$$u"
echo "    u$$$$$$\"   \"$$$\"   \"$$$$$$u"
echo "    \"$$$$\"      u$u       $$$$\""
echo "     $$$u       u$u       u$$$"
echo "     $$$u      u$$$u      u$$$"
echo "      \"$$$$uu$$$   $$$uu$$$$\""
echo "       \"$$$$$$$\"   \"$$$$$$$\""
echo "         u$$$$$$$u$$$$$$$u"
echo "          u$\"$\"$\"$\"$\"$\"$u"
echo "       uu$$$        $$$uu"
echo "      u$$$$          $$$$u"
echo "       $$$$$uu    uu$$$$$"
echo "        \"$$$$$$\"  \"$$$$$$\""
echo "          $$$$$$  $$$$$$"
echo "           \"$$$$  $$$$\""
echo ""
